# Generated by Django 5.2 on 2025-05-06 18:42

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_gender', models.CharField(choices=[('male', 'مرد'), ('female', 'زن'), ('any', 'فرقی ندارد')], default='any', max_length=10)),
                ('special_conditions', models.TextField(blank=True, null=True)),
                ('scheduled_time', django_jalali.db.models.jDateTimeField()),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('confirmed', 'تأیید شده'), ('completed', 'تکمیل شده'), ('canceled', 'لغو شده')], default='pending', max_length=20)),
            ],
            options={
                'verbose_name': 'درخواست',
                'verbose_name_plural': 'درخواست\u200cها',
            },
        ),
    ]
